// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Debug_screen_init(void)
{
    ui_Debug = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Debug, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Debug, &ui_img_189584499, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Debug, 120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDebug = lv_label_create(ui_Debug);
    lv_obj_set_width(ui_LabelDebug, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDebug, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDebug, -78);
    lv_obj_set_y(ui_LabelDebug, -170);
    lv_obj_set_align(ui_LabelDebug, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDebug, "Debug Log");
    lv_obj_set_style_text_font(ui_LabelDebug, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Debug, ui_event_Debug, LV_EVENT_ALL, NULL);

}
