// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Home, &ui_img_189584499, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Home, 160, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour, -60);
    lv_obj_set_y(ui_Hour, -90);
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "08");
    lv_obj_set_style_text_color(ui_Hour, lv_color_hex(0xE2C3F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hour, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Minute = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Minute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Minute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Minute, 30);
    lv_obj_set_y(ui_Minute, 10);
    lv_obj_set_align(ui_Minute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Minute, "45");
    lv_obj_set_style_text_color(ui_Minute, lv_color_hex(0xF4A1EA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Minute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Minute, &ui_font_Number_big, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weekday = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Weekday, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weekday, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weekday, 75);
    lv_obj_set_y(ui_Weekday, -125);
    lv_obj_set_align(ui_Weekday, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weekday, "星期一");
    lv_obj_set_style_text_font(ui_Weekday, &ui_font_Chinese, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 75);
    lv_obj_set_y(ui_Date, -90);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "08.10");
    lv_obj_set_style_text_font(ui_Date, &ui_font_DateFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Second = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Second, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Second, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Second, 122);
    lv_obj_set_y(ui_Second, 30);
    lv_obj_set_align(ui_Second, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Second, "15");
    lv_obj_set_style_text_color(ui_Second, lv_color_hex(0xB58DFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Second, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Second, &ui_font_SecondFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 73);
    lv_obj_set_y(ui_Label2, -62);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "2023");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_YearFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcHr = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_ArcHr, 75);
    lv_obj_set_height(ui_ArcHr, 75);
    lv_obj_set_x(ui_ArcHr, -100);
    lv_obj_set_y(ui_ArcHr, 100);
    lv_obj_set_align(ui_ArcHr, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ArcHr, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_ArcHr, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ArcHr, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcHr, 50);
    lv_obj_set_style_arc_width(ui_ArcHr, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcHr, lv_color_hex(0xBB0020), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcHr, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcHr, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcHr, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcHr, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcStep = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_ArcStep, 75);
    lv_obj_set_height(ui_ArcStep, 75);
    lv_obj_set_x(ui_ArcStep, -10);
    lv_obj_set_y(ui_ArcStep, 100);
    lv_obj_set_align(ui_ArcStep, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ArcStep, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_ArcStep, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ArcStep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcStep, 50);
    lv_obj_set_style_arc_width(ui_ArcStep, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcStep, lv_color_hex(0xEB8334), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcStep, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcStep, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcStep, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcStep, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ArcMental = lv_arc_create(ui_Home);
    lv_obj_set_width(ui_ArcMental, 75);
    lv_obj_set_height(ui_ArcMental, 75);
    lv_obj_set_x(ui_ArcMental, 80);
    lv_obj_set_y(ui_ArcMental, 100);
    lv_obj_set_align(ui_ArcMental, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ArcMental, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_ArcMental, LV_OBJ_FLAG_EVENT_BUBBLE);     /// Flags
    lv_obj_clear_flag(ui_ArcMental, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_value(ui_ArcMental, 50);
    lv_obj_set_style_arc_width(ui_ArcMental, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcMental, lv_color_hex(0x9B31BF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcMental, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcMental, 8, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcMental, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcMental, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelHR = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LabelHR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHR, -100);
    lv_obj_set_y(ui_LabelHR, 100);
    lv_obj_set_align(ui_LabelHR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHR, "85");
    lv_obj_set_style_text_font(ui_LabelHR, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTemp = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTemp, -119);
    lv_obj_set_y(ui_LabelTemp, 166);
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTemp, "温度");
    lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_TempFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNumTemp = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LabelNumTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNumTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNumTemp, -80);
    lv_obj_set_y(ui_LabelNumTemp, 165);
    lv_obj_set_align(ui_LabelNumTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelNumTemp, "23.5");
    lv_obj_set_style_text_font(ui_LabelNumTemp, &ui_font_TempNumberFont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeHR = lv_label_create(ui_Home);
    lv_obj_set_width(ui_LabeHR, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeHR, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeHR, -101);
    lv_obj_set_y(ui_LabeHR, 133);
    lv_obj_set_align(ui_LabeHR, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeHR, "HR");
    lv_obj_set_style_text_font(ui_LabeHR, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);

}
