// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
lv_obj_t * ui_Home;
lv_obj_t * ui_Hour;
lv_obj_t * ui_Minute;
lv_obj_t * ui_Weekday;
lv_obj_t * ui_Date;
lv_obj_t * ui_Second;
lv_obj_t * ui_Label2;
lv_obj_t * ui_ArcHr;
lv_obj_t * ui_ArcStep;
lv_obj_t * ui_ArcMental;
lv_obj_t * ui_LabelHR;
lv_obj_t * ui_LabelTemp;
lv_obj_t * ui_LabelNumTemp;
lv_obj_t * ui_LabeHR;

// SCREEN: ui_Sensor
void ui_Sensor_screen_init(void);
void ui_event_Sensor(lv_event_t * e);
lv_obj_t * ui_Sensor;
lv_obj_t * ui_LabelSensor;
lv_obj_t * ui_SensorTempurature;
lv_obj_t * ui_ChartTempurature;
lv_obj_t * ui_SensorAcceleration_;
lv_obj_t * ui_ChartAcceleration;
lv_obj_t * ui_LabelAcceX;
lv_obj_t * ui_LabelAcceY;
lv_obj_t * ui_LabelAcceZ;

// SCREEN: ui_Debug
void ui_Debug_screen_init(void);
void ui_event_Debug(lv_event_t * e);
lv_obj_t * ui_Debug;
lv_obj_t * ui_LabelDebug;

// SCREEN: ui_HearteRate
void ui_HearteRate_screen_init(void);
void ui_event_HearteRate(lv_event_t * e);
lv_obj_t * ui_HearteRate;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Sensor, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}
void ui_event_Sensor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Debug, LV_SCR_LOAD_ANIM_MOVE_LEFT, 250, 0);
    }
}
void ui_event_Debug(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Sensor, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 250, 0);
    }
}
void ui_event_HearteRate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Home_screen_init();
    ui_Sensor_screen_init();
    ui_Debug_screen_init();
    ui_HearteRate_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Home);
}
