// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Home
void ui_Home_screen_init(void);
void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Minute;
extern lv_obj_t * ui_Weekday;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_ArcHr;
extern lv_obj_t * ui_ArcStep;
extern lv_obj_t * ui_ArcMental;
extern lv_obj_t * ui_LabelHR;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelNumTemp;
extern lv_obj_t * ui_LabeHR;
// SCREEN: ui_Sensor
void ui_Sensor_screen_init(void);
void ui_event_Sensor(lv_event_t * e);
extern lv_obj_t * ui_Sensor;
extern lv_obj_t * ui_LabelSensor;
extern lv_obj_t * ui_SensorTempurature;
extern lv_obj_t * ui_ChartTempurature;
extern lv_obj_t * ui_SensorAcceleration_;
extern lv_obj_t * ui_ChartAcceleration;
extern lv_obj_t * ui_LabelAcceX;
extern lv_obj_t * ui_LabelAcceY;
extern lv_obj_t * ui_LabelAcceZ;
// SCREEN: ui_Debug
void ui_Debug_screen_init(void);
void ui_event_Debug(lv_event_t * e);
extern lv_obj_t * ui_Debug;
extern lv_obj_t * ui_LabelDebug;
// SCREEN: ui_HearteRate
void ui_HearteRate_screen_init(void);
void ui_event_HearteRate(lv_event_t * e);
extern lv_obj_t * ui_HearteRate;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_189584499);    // assets\bg2(1).png

LV_FONT_DECLARE(ui_font_Chinese);
LV_FONT_DECLARE(ui_font_DateFont);
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_SecondFont);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_TempFont);
LV_FONT_DECLARE(ui_font_TempNumberFont);
LV_FONT_DECLARE(ui_font_Title);
LV_FONT_DECLARE(ui_font_YearFont);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
