// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: SquareLine_Project

#include "../ui.h"

#define PPGARRAYSIZE 80
#define PPGSCALE     10000
lv_chart_series_t *ui_ChartPPG_series_1;
static lv_coord_t ui_ChartPPG_series_1_array[PPGARRAYSIZE] = { 0 };   // 窗口共4秒，提前降采样到20Hz
static int32_t ChartPPG_series_1_array_O[PPGARRAYSIZE] = { 0 }; // 窗口共4秒，提前降采样到20Hz
static uint8_t array1Pointer = 0;
static int32_t greenMax = -1e12;
static int32_t greenMin = 1e12;
static int32_t greenAvg = 0;

void ui_HearteRate_screen_init(void)
{
    ui_HearteRate = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HearteRate, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_HearteRate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHearteRate = lv_label_create(ui_HearteRate);
    lv_obj_set_width(ui_LabelHearteRate, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelHearteRate, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelHearteRate, -2);
    lv_obj_set_y(ui_LabelHearteRate, -136);
    lv_obj_set_align(ui_LabelHearteRate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHearteRate, "Sensor Panel 3 PPG");
    lv_obj_set_style_text_font(ui_LabelHearteRate, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartPPG = lv_chart_create(ui_HearteRate);
    lv_obj_set_width(ui_ChartPPG, 196);
    lv_obj_set_height(ui_ChartPPG, 104);
    lv_obj_set_x(ui_ChartPPG, 8);
    lv_obj_set_y(ui_ChartPPG, -55);
    lv_obj_set_align(ui_ChartPPG, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartPPG, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartPPG, PPGARRAYSIZE);
    lv_chart_set_range(ui_ChartPPG, LV_CHART_AXIS_PRIMARY_Y, 0, (uint16_t)(1000 + 200));
    lv_chart_set_range(ui_ChartPPG, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_chart_set_div_line_count(ui_ChartPPG, 10, 30);
    lv_chart_set_axis_tick(ui_ChartPPG, LV_CHART_AXIS_PRIMARY_X, 8, 3, 5, 5, true, 50);
    lv_chart_set_axis_tick(ui_ChartPPG, LV_CHART_AXIS_PRIMARY_Y, 8, 5, 5, 2, false, 50);
    lv_chart_set_axis_tick(ui_ChartPPG, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 0, 0, false, 25);
    ui_ChartPPG_series_1 = lv_chart_add_series(ui_ChartPPG, lv_color_hex(0x00FF00),
                                               LV_CHART_AXIS_PRIMARY_Y);
    // printf("ui_ChartPPG_series_1 0x%x\r\n", ui_ChartPPG_series_1);
    // lv_chart_set_ext_y_array(ui_ChartPPG, ui_ChartPPG_series_1, ui_ChartPPG_series_1_array);
    // printf("ui_ChartPPG_series_1 0x%x\r\n", ui_ChartPPG_series_1);
    lv_chart_set_ext_y_array(ui_ChartPPG, ui_ChartPPG_series_1, ui_ChartPPG_series_1_array);
    // lv_chart_set_update_mode(ui_ChartPPG, LV_CHART_UPDATE_MODE_SHIFT);
    lv_obj_set_style_width(ui_ChartPPG, 0, LV_PART_INDICATOR);
    lv_obj_set_style_height(ui_ChartPPG, 0, LV_PART_INDICATOR);

    lv_obj_add_event_cb(ui_HearteRate, ui_event_HearteRate, LV_EVENT_ALL, NULL);
}

void ui_UpdatePPGChart(int32_t green, int32_t red, int32_t ired)
{
    uint16_t greenValue = 0;
    if (array1Pointer < PPGARRAYSIZE) {
        ChartPPG_series_1_array_O[array1Pointer] = green;
        array1Pointer++;
    } else {
        for (uint8_t i = 0; i < PPGARRAYSIZE - 1; i++) {
            ChartPPG_series_1_array_O[i] = ChartPPG_series_1_array_O[i + 1];
        }
        ChartPPG_series_1_array_O[PPGARRAYSIZE - 1] = green;
    }

    greenMax = -1e16;
    greenMin = 1e16;
    greenAvg = 0;
    for (uint8_t i = 0; i < PPGARRAYSIZE; i++) {
        if (ChartPPG_series_1_array_O[i] > greenMax) {
            greenMax = ChartPPG_series_1_array_O[i];
        }
        if (ChartPPG_series_1_array_O[i] < greenMin) {
            greenMin = ChartPPG_series_1_array_O[i];
        }
        // greenAvg += ui_ChartPPG_series_1_array[i];
    }
    // greenAvg /= array1Pointer;

    // greenValue = (uint16_t)((green - greenMin) * 1000 / (greenMax - greenMin) + 100);
    // printf("greenValue %d\r\n", greenValue);
    // printf("greenMax %d\r\n", greenMax);
    // printf("greenMin %d\r\n", greenMin);

    for (uint8_t i = 0; i < PPGARRAYSIZE; i++) {
        ui_ChartPPG_series_1_array[i] = (uint16_t)((ChartPPG_series_1_array_O[i] - greenMin) * 1000 / (greenMax - greenMin) + 100);
    }
    lv_chart_refresh(ui_ChartPPG);
}